---
title: "plot-draft"
author: "Jeffray Tsai"
date: "5/1/2022"
output: html_document
---
```{r}
library(dplyr)
library(tidyr)
library(spdplyr)
library(plotly)
```


```{r}
setwd("/Users/tsaijeffray/Documents/GitHub/Group-E_Climate-Real-Estate/Shiny Draft")
bar_chart_data <- read.csv('bar_chart_data.csv')
coffeypark_bar_data <- bar_chart_data %>% filter(city == 'Coffey Park')
orleans_bar_data <- bar_chart_data %>% filter(city == 'New Orleans')
moore_bar_data <- bar_chart_data %>% filter(city == 'Moore')
grandisle_bar_data <- bar_chart_data %>% filter(city == 'Grand Isle')
buffalo_bar_data <- bar_chart_data %>% filter(city == 'Buffalo')
```

```{r}
onefourtwoohone <- buffalo_bar_data %>% filter(zip_code=='14201')
#we only want one zip code at a time 
plot_ly(onefourtwoohone, x=~date, y=~single_fam_val, group=~zip_code, color=~date, type='bar') %>% layout(legend = list(orientation = "h", 
                     xanchor = "center", 
                     x = 0.5,y=-0.2), yaxis = list(
      range=c(130000,145000)))
```

```{r}
buffalo_data <- bar_chart_data %>% filter(city=='Buffalo')
plot_ly(buffalo_data, x=~zip_code, y=~single_fam_val, group=~zip_code, color=~date, type='bar')
```



```{r}
setwd("/Users/tsaijeffray/Documents/GitHub/Group-E_Climate-Real-Estate/Shiny Draft")
line_chart_data <- read.csv('line_chart_data.csv')
plot_ly(line_chart_data, x=~date, y=~avg_single_fam_val, type = 'scatter', mode = 'lines',color= ~city) 
# %>% add_trace(x =as.Date("2018-10-01"),type = 'scatter', mode = 'lines', line = list(color = 'black'),name = '') 
```

```{r setup, include=FALSE}
output$line_chart_neworleans <- renderPlotly({plot_ly(refined_orleans_data, x = ~date, y =~single_fam_val, type = 'scatter', mode = 'lines', name = 'New Orleans Median Prices')})
output$line_chart_moore <- renderPlotly({plot_ly(refined_moore_data, x = ~date, y =~single_fam_val, type = 'scatter', mode = 'lines', name = 'Moore Median Prices')})
output$line_chart_buffalo <- renderPlotly({plot_ly(refined_buffalo_data, x = ~date, y =~single_fam_val, type = 'scatter', mode = 'lines', name = 'Buffalo Median Prices')})
output$line_chart_coffeypark <- renderPlotly({plot_ly(refined_coffey_park_data, x = ~date, y =~single_fam_val, type = 'scatter', mode = 'lines', name = 'Coffey Park Median Prices')})
output$line_chart_grandisle <- renderPlotly({plot_ly(refined_orleans_data, x = ~date, y =~single_fam_val, type = 'scatter', mode = 'lines', name = 'Grand Isle Median Prices')})

```

```{r}
output$temp <- renderPrint({
    input$map_marker_click$lng
  })
  
  
  output$bar_chart_neworleans <- renderPlotly({plot_ly(temp <- orleans_bar_data, 
                                                       x=~date, y=~single_fam_val, 
                                                       group=~zip_code, color=~date, type='bar') %>% 
                          layout(legend = list(orientation = "h", 
                           xanchor = "center", 
                           x = 0.5,y=-0.2), yaxis = list(range=c(130000,145000)))})
```

```{r}
output$bar_chart_neworleans <- renderPlotly({plot_ly(temp <- orleans_bar_data, x=~date, y=~single_fam_val, group=~zip_code, color=~date, type='bar') %>% layout(legend = list(orientation = "h", 
                     xanchor = "center", 
                     x = 0.5,y=-0.2), yaxis = list(
      range=c(130000,145000)))})
output$bar_chart_moore <- renderPlotly({plot_ly(refined_moore_data, x = ~zip_code, y = ~single_fam_val, type = 'bar', mode = 'lines', name = 'Moore Prices by Zip Codes')})
output$bar_chart_buffalo <- renderPlotly({plot_ly(refined_buffalo_data, x = ~zip_code, y = ~single_fam_val, type = 'bar', mode = 'lines', name = 'Buffalo Prices by Zip Codes')})
output$bar_chart_coffeypark <- renderPlotly({plot_ly(refined_coffey_park_data, x = ~zip_code, y = ~single_fam_val, type = 'bar', mode = 'lines', name = 'Coffey Park Prices by Zip Codes')})
output$bar_chart_grandisle <- renderPlotly({plot_ly(refined_grandisle_data, x = ~zip_code, y = ~single_fam_val, type = 'bar', mode = 'lines', name = 'Grand Isle Prices by Zip Codes')})
```